language: python
python:
  - "2.7"
  - "3.6"
install:
  - pip install flake8 yapf pytest
  - python setup.py install
script:
  - pytest xdg_json_cache
  - flake8 xdg_json_cache
  - yapf -d -r xdg_json_cache
